tasks:
  - init : |
      wget https://github.com/jeremyk6/TP_POSTGIS/releases/download/rootfs/rootfs.tar.gz
      tar xvf rootfs.tar.gz
      rm -rf rootfs.tar.gz
      sudo mkdir rootfs/TP_POSTGIS
      sudo mount --bind TP_POSTGIS rootfs/TP_POSTGIS
  - before : |
      sudo mount -t sysfs /sys rootfs/sys
      sudo mount -t proc /proc rootfs/proc
      sudo mount -R /dev rootfs/dev
      sudo mount -t devpts /dev/pts rootfs/dev/pts
    command : sudo chroot rootfs /bin/bash -c "su - -c /root/start.sh"

  ports :
    - port: 8080
      onOpen: open-browser
    - port: 6080
      onOpen: open-browser